# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stacked', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 21, 14, 18, 44, 561346, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 21, 14, 18, 44, 541172, tzinfo=utc)),
        ),
    ]
