# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stacked', '0007_auto_20160521_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 21, 14, 59, 27, 484307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 21, 14, 59, 27, 462507, tzinfo=utc)),
        ),
    ]
