# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stacked', '0011_auto_20160522_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 22, 14, 9, 2, 332212, tzinfo=utc)),
        ),
    ]
