# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stacked', '0013_auto_20160522_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 0, 35, 15, 897261, tzinfo=utc)),
        ),
    ]
